output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
    dbname  = "tts"
    host    = "localhost"
    port    = 3306
    user    = "app_user"
    pass    = "superuser"
    sslmode = "false"
    tinyint_as_int = true