// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ChatContextRequest defines model for ChatContextRequest.
type ChatContextRequest struct {
	Question *string `json:"question,omitempty"`
}

// ChatContextResponse defines model for ChatContextResponse.
type ChatContextResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// ContextPdf defines model for ContextPdf.
type ContextPdf struct {
	File openapi_types.File `json:"file" validate:"required"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// JoinPdfFiles defines model for JoinPdfFiles.
type JoinPdfFiles struct {
	Files []openapi_types.File `json:"files"`
}

// SignPdfFile defines model for SignPdfFile.
type SignPdfFile struct {
	File openapi_types.File `json:"file" validate:"required"`
	Key  string             `json:"key" validate:"required"`
}

// Success defines model for Success.
type Success struct {
	Message string `json:"message"`
}

// SummarizePdf defines model for SummarizePdf.
type SummarizePdf struct {
	File openapi_types.File `json:"file" validate:"required"`
}

// SummarizeResponse defines model for SummarizeResponse.
type SummarizeResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// TtsResponse defines model for TtsResponse.
type TtsResponse struct {
	Data *struct {
		Url *string `json:"url,omitempty"`
	} `json:"data,omitempty"`
}

// VerifyPdfFile defines model for VerifyPdfFile.
type VerifyPdfFile struct {
	File openapi_types.File `json:"file" validate:"required"`
	Key  string             `json:"key" validate:"required"`
}

// ChatContextJSONRequestBody defines body for ChatContext for application/json ContentType.
type ChatContextJSONRequestBody = ChatContextRequest

// JoinPdfFilesMultipartRequestBody defines body for JoinPdfFiles for multipart/form-data ContentType.
type JoinPdfFilesMultipartRequestBody = JoinPdfFiles

// SignPdfFileMultipartRequestBody defines body for SignPdfFile for multipart/form-data ContentType.
type SignPdfFileMultipartRequestBody = SignPdfFile

// SummarizePdfMultipartRequestBody defines body for SummarizePdf for multipart/form-data ContentType.
type SummarizePdfMultipartRequestBody = SummarizePdf

// UploadContextPdfMultipartRequestBody defines body for UploadContextPdf for multipart/form-data ContentType.
type UploadContextPdfMultipartRequestBody = ContextPdf

// VerifyPdfFileMultipartRequestBody defines body for VerifyPdfFile for multipart/form-data ContentType.
type VerifyPdfFileMultipartRequestBody = VerifyPdfFile
