// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUQW/bPAz9Kyq/7+jE7tqigE/tgB162DC026noQZEZR4UtaSJdpAjy3wdKdtqkRbdD",
	"sJMFU9R75HvkBozvg3fomKDeAJkV9jodv8TooxxC9AEjW0y/eyTSLcoR17oPHUINg8N1QMPYKExpBfBz",
	"kAhxtK6FbQHUDe1+1kI3s4i/BiR+m7AtQGI2YgP1fc4udugPu/t+8YiGBeBuMAaJ/pIy5dsnf0T+GDIE",
	"H/l2LOINMvbadvu44+mKkXhufP8Gv4D1zOtgZ8Y32KKb4ZqjnrFu05NPurONZknYsRTKr4pskEy0ga13",
	"UMONCwOrMayWPirKrKcvFK/o/VhZUpam+yfHoud0fyDAT8Kovsnvo0AcqObyw1mAj3wjidYtvbxsvGNt",
	"+JVyEC13ekGn59X5VSv/Rs1yPXCbw+KF/a5fK7JSqLr+fpOabh3hS8/VCDWX4i2nhoxmkgwo4Akj5adO",
	"59W8EgQf0OlgoYazeTU/gwKC5lXqSamDLZmpnDQVK/psSTGkFlo3TbKD8LjbST8O4GffPE8tQJfydAid",
	"NSmzfCShMu0HOf0fcQk1/Fe+LJBy3B7lwVikHh+acq8btFf6i44cB0zCUvCO8kx9qk6PSDSvjHcYjiH1",
	"dXTOtoDzqjoact6u73Ym+VvtmlfAxb/AvcP4hFFN8QJo6Hsdnz8WKz1EKZWgvt/AEGVqVsyB6rLcrDyx",
	"jMpWDCqu1tHqRZeVnIJ5Zy310DHU0HmjOwnVl9XlhSA8bH8HAAD//8g4tZCnBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
