// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUQW/bPAz9Kyq/7+jZ7tqigE/tgB162DC026noQZGZRIUtaSJdtAjy3wdKdpqkQbpD",
	"sZMJUfR7fI/UCozvg3fomKBZAZkl9jqFX2P0UYIQfcDIFtNxj0R6gRLis+5Dh9DA4PA5oGFsFaayAvgl",
	"SIY4WreAdQHUDYvdqpluP0X8PSDx24J1AZKzEVto7nN1sUF/2Nz3s0c0LAB3gzFI9JeUKd8+eRf5OGQI",
	"PvLt2MQbZOy17XZxx+iKkbg0vj8k1RbhFslEG9h6Bw3cuDCwGtNq7qOizGD6QrEF9XNpSVma7p8cgnK6",
	"3xPmF2FU3+X4PWVcvpSbPOaNFFo39wJkvGNteEsdiJY7PaPT8/r8aiFnoy6ZG9zmtLDdVeNakRXS6vrH",
	"TRLDOsJXLdQIVUojllNzo2FSAQU8YaT8q9OyLmtB8AGdDhYaOCvr8gwKCJqXycxKB1sxUzVpLXb7bLuY",
	"roXWTZtsEh53G0vGIf/i25dJAnSpTofQWZMqq0cSKtMOSvR/xDk08F/1uqTVuKHV3ugljfeHZUcN2mn9",
	"1UeOAyZjKXhHeW4/16cfSDSv5QGGY0p9GydnXcB5XX8Ycn7BDirzpDvbqo14BVz8C9w7jE8Y1ZQvgIa+",
	"1/HluFnpR5RKCZr7FQxRtmbJHKipqtXSE8uqrGVAZap1tHrWZSenZH5L5nroGBrovNGdpJrL+vJCEB7W",
	"fwIAAP//RfbzzgsGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
