// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AudioSummarizeRequest defines model for AudioSummarizeRequest.
type AudioSummarizeRequest struct {
	File openapi_types.File `json:"file" validate:"required"`
}

// AudioSummarizeResponse defines model for AudioSummarizeResponse.
type AudioSummarizeResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// AudioTranscriptRequest defines model for AudioTranscriptRequest.
type AudioTranscriptRequest struct {
	File openapi_types.File `json:"file" validate:"required"`
}

// AudioTranscriptResponse defines model for AudioTranscriptResponse.
type AudioTranscriptResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// JoinMP3Files defines model for JoinMP3Files.
type JoinMP3Files struct {
	Files []openapi_types.File `json:"files"`
}

// Success defines model for Success.
type Success struct {
	Message string `json:"message"`
}

// TtsRequest defines model for TtsRequest.
type TtsRequest struct {
	// Lang Language code for the speech (e.g., "en" for English, "id" for Indonesian).
	Lang *string `json:"lang,omitempty"`
	Text string  `json:"text" validate:"required"`
}

// TtsResponse defines model for TtsResponse.
type TtsResponse struct {
	Data *struct {
		Url *string `json:"url,omitempty"`
	} `json:"data,omitempty"`
}

// VideoSummarizeRequest defines model for VideoSummarizeRequest.
type VideoSummarizeRequest struct {
	// Url input youtube URL
	Url string `json:"url" validate:"required"`
}

// VideoSummarizeResponse defines model for VideoSummarizeResponse.
type VideoSummarizeResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// VideoTranscriptRequest defines model for VideoTranscriptRequest.
type VideoTranscriptRequest struct {
	// Url input youtube URL
	Url string `json:"url" validate:"required"`
}

// VideoTranscriptResponse defines model for VideoTranscriptResponse.
type VideoTranscriptResponse struct {
	Data *struct {
		Output *string `json:"output,omitempty"`
	} `json:"data,omitempty"`
}

// TextToSpeechJSONRequestBody defines body for TextToSpeech for application/json ContentType.
type TextToSpeechJSONRequestBody = TtsRequest

// AudioSummarizeMultipartRequestBody defines body for AudioSummarize for multipart/form-data ContentType.
type AudioSummarizeMultipartRequestBody = AudioSummarizeRequest

// AudioTranscriptMultipartRequestBody defines body for AudioTranscript for multipart/form-data ContentType.
type AudioTranscriptMultipartRequestBody = AudioTranscriptRequest

// JoinMP3FilesMultipartRequestBody defines body for JoinMP3Files for multipart/form-data ContentType.
type JoinMP3FilesMultipartRequestBody = JoinMP3Files

// ReadTextToSpeechJSONRequestBody defines body for ReadTextToSpeech for application/json ContentType.
type ReadTextToSpeechJSONRequestBody = TtsRequest

// VideoSummarizeJSONRequestBody defines body for VideoSummarize for application/json ContentType.
type VideoSummarizeJSONRequestBody = VideoSummarizeRequest

// VideoTranscriptJSONRequestBody defines body for VideoTranscript for application/json ContentType.
type VideoTranscriptJSONRequestBody = VideoTranscriptRequest
