// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// JoinMP3Files defines model for JoinMP3Files.
type JoinMP3Files struct {
	Files []openapi_types.File `json:"files"`
}

// Success defines model for Success.
type Success struct {
	Message string `json:"message"`
}

// TtsRequest defines model for TtsRequest.
type TtsRequest struct {
	// Lang Language code for the speech (e.g., "en" for English, "id" for Indonesian).
	Lang *string `json:"lang,omitempty"`
	Text string  `json:"text"`
}

// TtsResponse defines model for TtsResponse.
type TtsResponse struct {
	Data *struct {
		Url *string `json:"url,omitempty"`
	} `json:"data,omitempty"`
}

// TextToSpeechJSONRequestBody defines body for TextToSpeech for application/json ContentType.
type TextToSpeechJSONRequestBody = TtsRequest

// JoinMP3FilesMultipartRequestBody defines body for JoinMP3Files for multipart/form-data ContentType.
type JoinMP3FilesMultipartRequestBody = JoinMP3Files

// ReadTextToSpeechJSONRequestBody defines body for ReadTextToSpeech for application/json ContentType.
type ReadTextToSpeechJSONRequestBody = TtsRequest
