// Package support provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package support

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Success defines model for Success.
type Success struct {
	Message string `json:"message"`
}

// SupportRequest defines model for SupportRequest.
type SupportRequest struct {
	Email string `json:"email" validate:"required"`

	// Message Input message for support support
	Message string `json:"message" validate:"required"`
	Name    string `json:"name" validate:"required"`
}

// InsertSupportJSONRequestBody defines body for InsertSupport for application/json ContentType.
type InsertSupportJSONRequestBody = SupportRequest
